import { NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { isMockMode } from "@/lib/supabase/mock-mode";

/**
 * POST /api/bookings — create a booking.
 *
 * Accepts the flat payload the booking wizard sends (StepConfirmation):
 *   { reference, product, pass_id, cabana_id, event_id, visit_date,
 *     adults, children, total_price, payment_method,
 *     full_name, phone, special_requests, qr_code_token?, lang? }
 *
 * `full_name` + `phone` are the walk-in guest's contact — stored on the
 * booking (guest_name / guest_phone) because a day-pass booker is usually
 * not an authenticated user. `qr_code_token` and `lang` from the client are
 * ignored: the DB generates the QR token; lang is UI-only.
 *
 * Insert uses the SERVICE-ROLE admin client so anonymous guest checkout is
 * not blocked by RLS (the anon client's insert policy requires user_id =
 * auth.uid()). In mock mode we log + echo so the flow is demoable offline.
 *
 * Columns owned by the DB (never taken from the client):
 *   id · qr_code_token · created_at · updated_at · status/payment_status
 *   default to 'pending' (the payment webhook promotes them).
 */

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const payloadSchema = z
  .object({
    reference: z.string().min(3).max(40),
    product: z.enum(["pass", "cabana", "event"]),
    pass_id: z.string().nullish(),
    cabana_id: z.string().nullish(),
    event_id: z.string().nullish(),
    visit_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "expected YYYY-MM-DD"),
    adults: z.number().int().min(0).default(0),
    children: z.number().int().min(0).default(0),
    total_price: z.number().int().min(0),
    payment_method: z.enum(["baridi", "cib", "cash"]),
    full_name: z.string().max(120).nullish(),
    phone: z.string().max(40).nullish(),
    special_requests: z.string().max(1000).nullish(),
    // Accepted but ignored — DB owns the token; lang is UI-only.
    qr_code_token: z.string().nullish(),
    lang: z.string().max(5).nullish(),
  })
  .refine(
    (d) =>
      (d.product === "pass" && !!d.pass_id) ||
      (d.product === "cabana" && !!d.cabana_id) ||
      (d.product === "event" && !!d.event_id),
    { message: "product must match its *_id (pass_id / cabana_id / event_id)" },
  );

export async function POST(request: Request) {
  let json: unknown;
  try {
    json = await request.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Invalid JSON body" }, { status: 400 });
  }

  const parsed = payloadSchema.safeParse(json);
  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, error: "Validation failed", issues: parsed.error.flatten() },
      { status: 422 },
    );
  }
  const p = parsed.data;

  // ---- Mock mode: no database, log + echo --------------------------------
  if (isMockMode()) {
    console.info("[bookings] mock insert", {
      reference: p.reference,
      product: p.product,
      visit_date: p.visit_date,
    });
    return NextResponse.json({ ok: true, mock: true, reference: p.reference }, { status: 201 });
  }

  // ---- Live mode: insert via service-role (bypasses anon RLS) -------------
  const admin = createAdminClient();
  if (!admin) {
    return NextResponse.json(
      { ok: false, error: "Supabase service client unavailable" },
      { status: 503 },
    );
  }

  const row = {
    reference: p.reference,
    product: p.product,
    pass_id: p.pass_id ?? null,
    cabana_id: p.cabana_id ?? null,
    event_id: p.event_id ?? null,
    visit_date: p.visit_date,
    adults: p.adults,
    children: p.children,
    total_price: p.total_price,
    payment_method: p.payment_method,
    guest_name: p.full_name ?? null,
    guest_phone: p.phone ?? null,
    special_requests: p.special_requests ?? null,
    // status / payment_status default to 'pending'; qr_code_token generated by DB.
  };

  const { data, error } = await admin
    .from("bookings")
    .insert(row)
    .select()
    .single();

  if (error) {
    const status = error.code === "23505" ? 409 : 500;
    console.error("[bookings] insert failed", error);
    return NextResponse.json({ ok: false, error: error.message, code: error.code }, { status });
  }

  return NextResponse.json({ ok: true, booking: data }, { status: 201 });
}
